// <auto-generated />
using System;
using IoTNetwork.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IoTNetwork.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IoTNetworkDbContext))]
    partial class IoTNetworkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IoTNetwork.Core.Domain.Entities.NodeDataDay", b =>
                {
                    b.Property<string>("NodeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("DayUtc")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NodeId", "DayUtc");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_node_data_days_node");

                    b.ToTable("node_data_days", (string)null);
                });

            modelBuilder.Entity("IoTNetwork.Core.Domain.Entities.TelemetryReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Co2")
                        .HasColumnType("double precision");

                    b.Property<double?>("Humidity")
                        .HasColumnType("double precision");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double?>("NoiseLevel")
                        .HasColumnType("double precision");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId", "TimestampUtc")
                        .HasDatabaseName("ix_telemetry_node_time");

                    b.ToTable("telemetry_readings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
